### ISSUE TITLE
图片上传无法加载

### ISSUE THREAD

**Issue by glen8** [huhx/flutter_oss_aliyun#17]
4.1.5版本上传到阿里云的图片 flutter 无法加载报错
回退到4.1.4正常

**Comment by huhx** [comment]
调用什么方法上传的文件

**Comment by huhx** [comment]
> 调用什么方法上传的文件以及错误信息是什么

**Comment by huhx** [comment]
> 4.1.5版本上传到阿里云的图片 flutter 无法加载报错
> 回退到4.1.4正常

调用什么方法上传的文件以及错误信息是什么

**Comment by huhx** [comment]
v4.1.6可以work
