### ISSUE TITLE
打开vpn时，上传图片Dio报错。

### ISSUE THREAD

**Issue by HelloBitches** [huhx/flutter_oss_aliyun#18]
如果我不开vpn，一切正常。
如果打开vpn，调用await Client().putObject(imageData, fileKey).then((re.Response value)
报错：
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/44893802/208383773-d4e2dcf1-24f5-46f3-a060-060094f1cc05.png">
麻烦看看这是什么原因

**Comment by huhx** [comment]
1、这种情况是发生在模拟器吗？如果是，在连接vpn时可以在浏览器访问网页，看是否可访问
2、如果能够访问，可以尝试清除avd的数据或者检查你的DNS setting

这个问题应该是DNS查找的问题，如果这个issue仍旧存在，可以再做讨论
