### ISSUE TITLE
批量上传文件之后返回的信息是什么

### ISSUE THREAD

**Issue by tiansuo** [huhx/flutter_oss_aliyun#19]
批量上传完文件之后，需要获取文件在阿里云上的信息，比如id，url之类的信息，返回的内容是什么样的

**Comment by huhx** [comment]
1. flutter_oss_aliyun提供了根据fileKey查询文件的元信息。
```dart
final Response<dynamic> resp = await Client().getObjectMeta("aaa.csv");
```
response如下：

<img width="400" alt="image" src="https://user-images.githubusercontent.com/15972372/209052513-4889de58-461e-4ef4-a53b-a9ca438f981b.png">

2. 如果想得到可直接访问的url地址，可以使用

单个文件：
```dart
final String url = await Client().getSignedUrl("aaa.txt");
```
多个文件：
```dart
final Map<String, String> result =  await Client().getSignedUrls( ["aaa.jpg", "bbb.jpg"]);
```

可以参考oss的文档：
post object: https://help.aliyun.com/document_detail/31978.html
get metadata: https://help.aliyun.com/document_detail/31985.html

**Comment by ChillChian** [comment]
var res = Client().putObjectFiles(fileList)
批量上传文件的返回值怎么解析呢，这里打印res是空

**Comment by huhx** [comment]
> var res = Client().putObjectFiles(fileList) 批量上传文件的返回值怎么解析呢，这里打印res是空

你好，这边期望得到什么样的信息呢？目前aliyun提供的上传文件接口没有返回什么信息，
可以参考文档：
post object: https://help.aliyun.com/document_detail/31978.html
get metadata: https://help.aliyun.com/document_detail/31985.html

如果有好的建议或者需求，可以提出来 。

**Comment by tiansuo** [comment]
好的，感谢


| |
绿化小能手
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年01月5日 21:31 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [huhx/flutter_oss_aliyun] 批量上传文件之后返回的信息是什么 (Issue #19) |

var res = Client().putObjectFiles(fileList) 批量上传文件的返回值怎么解析呢，这里打印res是空

你好，这边期望得到什么样的信息呢？目前aliyun提供的上传文件接口没有返回什么信息，
可以参考文档：
post object: https://help.aliyun.com/document_detail/31978.html
get metadata: https://help.aliyun.com/document_detail/31985.html

如果有好的建议或者需求，可以提出来 。
