### ISSUE TITLE
flutter web端 Refused to set unsafe header "date"

### ISSUE THREAD

**Issue by zbjumper** [huhx/flutter_oss_aliyun#20]
设置http header时，HttpRequest对象在setRequestHeader时，会报错 Refused to set unsafe header "date"

**Comment by huhx** [comment]
可以提供多的信息，以供分析问题。简单可以重现问题的代码最好

**Comment by zbjumper** [comment]
用项目下的example目录下的main.dart就可以复现，把Client.init替换成我们自己的信息，改为

**Comment by zbjumper** [comment]
用项目下的example目录下的main.dart就可以复现，把Client.init替换成我们自己的信息，改为

`    Client.init(
      // stsUrl: "server sts url",
      ossEndpoint: "oss-cn-hangzhou.aliyuncs.com",
      bucketName: "****-****-****",
      tokenGetter: () async {
        return '''
{
  "AccessKeyId": "STS.***************Qyc8W7T",
  "AccessKeySecret": "3EcNPigME4FrF************P8xTyn52xp4C",
  "SecurityToken": "CAISuAJ1q6Ft5B2yfSjIr5f/LOzt3IwT8/Wed03gnnMwXfZP15Kctjz2IH1EenNrBuwavvg+nm1V6/kblq11TINIHfsR1UHMtsY5yxioRqackTTcj9Vd+n/MewW6**********************jQJr5LxaTSlWS7CU/iOkoU1VskLeQO6YDFafuc0QDFvs8gHL3DcGO+wOxrx+ArqAVFvpxB3hBEri/a2ydbO7QHF3h+oiL0aqoL8Z4S+btEpJ4t2XNry2utqe+3cyyNK8F8Rq+As1PYeoG2d4JacBlBe7lLEEZKNq4I/clEpOPRqS/YY/Kigr5Ai5LyPzbaQ4g1WIORY***************************************c3ShLkA==",
  "Expiration": "2022-12-26T02:47:39.505Z"
}''';
      },
    );`


“一些关键的信息，我替换成*****了”

chrome控制台报错如下： 
![image](https://user-images.githubusercontent.com/4495144/209489737-538748b1-d999-4059-8f2c-0ce150272ef3.png)
![image](https://user-images.githubusercontent.com/4495144/209489626-b60c1a60-cf31-4e0b-aca9-5ca4c2b4093a.png)

**Comment by huhx** [comment]
感谢你提供的信息，w3c规定，当请求的header匹配到Date时，将被终止。移动端就不会出现问题，

https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

目前已修复：v5.0.1
