### ISSUE TITLE
现在上传入参是List<int> fileData, 希望能加一个Uint8List  fileData

### ISSUE THREAD

**Issue by herowws** [huhx/flutter_oss_aliyun#21]
await Client().putObject(
  bytes,
  "test.txt",
  onSendProgress: (count, total) {
    debugPrint("sent = $count, total = $total");
  },
  onReceiveProgress: (count, total) {
    debugPrint("received = $count, total = $total");
  }
);

**Comment by huhx** [comment]
Uint8List 是实现了 List<int>的，所以putObject第一个参数是可以接收Uint8List的吧。
```dart
abstract class Uint8List implements List<int>, _TypedIntList {
....
}
```
Uint8List来自于：library dart.typed_data;

测试代码：
```dart
final Response<dynamic> resp = await Client().putObject(
  Uint8List.fromList("aaa".codeUnits),
  "test.txt"
);
```
