### ISSUE TITLE
上传进度回调，只回调了一次。

### ISSUE THREAD

**Issue by HelloBitches** [huhx/flutter_oss_aliyun#22]
![1111](https://user-images.githubusercontent.com/44893802/210032420-fa3d1408-f0fa-4e3a-b647-ea365eb040f3.png)
我使用 await Client().putObject上传图片时，希望拿到图片上传进度的回调。
但是onSendProgress回调实际上只回调了一次，
这样的话，我没法在页面上展示上传进度了，类似于从1%-100%。
希望大佬可以修复该问题。

**Comment by HelloBitches** [comment]
我使用的版本：5.0.0

**Comment by huhx** [comment]
Fix in v5.0.2，目前每64KB回调一次。后面可能会考虑根据文件大小来确定chunk size.

**Comment by HelloBitches** [comment]
好的，多谢大佬，必须星星💗

**Comment by HelloBitches** [comment]
> Fix in v5.0.2，目前每64KB回调一次。后面可能会考虑根据文件大小来确定chunk size.
好的，多谢大佬，必须星星💗
