### ISSUE TITLE
什么时候支持web端？

### ISSUE THREAD

**Issue by yk81708090** [huhx/flutter_oss_aliyun#27]
是否有计划支持web端？

**Comment by huhx** [comment]
你好，这个库是全平台支持的，你在web端使用是碰到什么问题了吗？

**Comment by yk81708090** [comment]
[flutter_oss_aliyun 5.1.4](https://pub.flutter-io.cn/packages/flutter_oss_aliyun)  这里并没有选中支持web，我先试试是否可以在web上跑起来。

**Comment by huhx** [comment]
好的，我也会去看下为什么pub上面没有显示对web的support

**Comment by huhx** [comment]
6.0.0 fully support Web
