### ISSUE TITLE
Accept better `tokenGetter` on `init`

### ISSUE THREAD

**Issue by kj415j45** [huhx/flutter_oss_aliyun#32]
In my opinion, `tokenGetter` should have a `FutureOr<Auth> Function()?` type.

Here're 2 changes:
1. Change the actual acceptable type to `Auth` so that we can construct it manually with `Auth(...)` rather than convert return value from our function into a patterned json. For example, [Aliyun's TypeScript STS SDK `@alicloud/sts20150401`](https://github.com/aliyun/alibabacloud-typescript-sdk/tree/master/sts-20150401) would return [a **camelCase** json](https://github.com/aliyun/alibabacloud-typescript-sdk/blob/acb22a7a6b387f835ea17ff2f562f8b10d792dec/sts-20150401/src/client.ts#L344-L356), while the patterned json use [a **PascalCase** json](https://github.com/huhx/flutter_oss_aliyun/blob/2653162f8407400a3a88f1b47c96eeeab0a01625/lib/src/client.dart#L651-L661). As a result, we have to make a conversion here.
2. Replace `Future<T>` with `FutureOr<T>`, since it would allow user to write simpler code here rather than wrap it with `() async =>` or something alike while the token can be access synchronously.

**Comment by huhx** [comment]
感谢你的建议，在6.0.0中已实现
