### ISSUE TITLE
这个能改改吗

### ISSUE THREAD

**Issue by bhk545145** [huhx/flutter_oss_aliyun#40]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'
#0      Client.init.<anonymous closure> (package:flutter_oss_aliyun/src/client.dart:46:45)
<asynchronous suspension>
#1      AuthMixin.getAuth (package:flutter_oss_aliyun/src/auth_mixin.dart:13:14)
<asynchronous suspension>
#2      Client.putObject (package:flutter_oss_aliyun/src/client.dart:256:23)
<asynchronous suspension>

**Comment by huhx** [comment]
可以提供一个简单的可以复现上述错误的代码吗？

**Comment by bhk545145** [comment]
我已经从外部解决了
