### ISSUE TITLE
请问大家是如何获得token的呢？

### ISSUE THREAD

**Issue by Mae623** [huhx/flutter_oss_aliyun#41]
产品文档看了，使用STS SDK和调用STS服务的AssumeRole接口两种方式，都不知道怎么在flutter里用Dart语言实现😭
https://help.aliyun.com/document_detail/100624.html?spm=a2c4g.375246.0.0
想知道大家是如何获得临时访问凭证呢？
谢谢！

**Comment by huhx** [comment]
我这边是有一个App服务器使用STS SDK暴露一个接口给flutter client使用，该接口返回结构
```json
{
"SecurityToken": "security token",
"AccessKeyId": "key id",
"StatusCode": 200,
"AccessKeySecret": "secret",
"Expiration": "2023-07-07T15:03:06Z"
}
```

**Comment by Mae623** [comment]
> 我这边是有一个App服务器使用STS SDK暴露一个接口给flutter client使用，该接口返回结构
> 
> ```json
> {
> "SecurityToken": "security token",
> "AccessKeyId": "key id",
> "StatusCode": 200,
> "AccessKeySecret": "secret",
> "Expiration": "2023-07-07T15:03:06Z"
> }
> ```

好的好的，谢谢大佬~
