### ISSUE TITLE
如何处理多个Bucket的情况？

### ISSUE THREAD

**Issue by yuanjiong** [huhx/flutter_oss_aliyun#42]
如题，我有多个Bucket，但是在初始化方法中就需要指定一个Bucket，这种情况下，如何操作不同的Bucket？

**Comment by yuanjiong** [comment]
附加：多个Bucket在不同的区域

**Comment by huhx** [comment]
你好，在init方法里面指定的是默认的bucket。
1. 第一个问题：在实际的方法里面，你可以指定bucketName。例如`putObject`方法可以。
2. 第二个问题：目前插件还未同时支持多个region的操作

**Comment by yuanjiong** [comment]
> 你好，在init方法里面指定的是默认的bucket。
> 
> 1. 第一个问题：在实际的方法里面，你可以指定bucketName。例如`putObject`方法可以。
> 2. 第二个问题：目前插件还未同时支持多个region的操作

多谢，🤝
