### ISSUE TITLE
请求使用帮助，我无法使用ak以访问aliyun oss 

### ISSUE THREAD

**Issue by WutangNailao** [huhx/flutter_oss_aliyun#45]
很抱歉在此打扰各位开发者，但我没在网上找到相关帮助，实在抱歉

在`自定义authGetter得到Auth` 阶段，我尝试使用ak来完成Client.init(),我现在得到了阿里云oss服务的ak，毫无疑问它是正确的，这在ossbrowser中得到了验证。

`Auth(
      accessKey: OssConfig.accessKeyId,
      accessSecret: OssConfig.accessKeySecret,
      expire: DateTime.now().toIso8601String(),
      secureToken: 'token',
    )`

这是我的Auth函数，我不明白哪里出了问题，我也无法得知如何去获取token，如果有人能帮助我，我将不胜感激。Thank you

**Comment by huhx** [comment]
我看到你关闭了issue，是问题得到解决了吗
