### ISSUE TITLE
自定义auth的方式可行吗？有没有具体例子可以参考呢？

### ISSUE THREAD

**Issue by wangguodong8602** [huhx/flutter_oss_aliyun#47]
<img width="593" alt="image" src="https://github.com/huhx/flutter_oss_aliyun/assets/52062388/112db9cc-3422-4822-9b1a-61e9faab73e6">
secureToken 这个值应该填什么内容呢

**Comment by huhx** [comment]
这个设计是基于阿里云的文档来的：https://help.aliyun.com/zh/oss/developer-reference/use-temporary-access-credentials-provided-by-sts-to-access-oss#p-osc-r0m-u63

后端有个api，会返回accessKey和accessSecret和secureToken这些信息。

**Comment by wangguodong8602** [comment]
好的  我来看着文档琢磨琢磨吧
