### ISSUE TITLE
文件样式(Style)功能添加

### ISSUE THREAD

**Issue by JianJia2018** [huhx/flutter_oss_aliyun#48]
我在`client.dart=>getSignedUrl`方法里面加了一个`"x-oss-process": process,`参数, 但是浏览器打开链接403, 发现这个要在`Signature`参数里面添加签名后才有效.

目前尝试了在`auth.dart->getSignature=>stringToSign`第二个参数以及`"${_getResourceString(bucket, key)}?security-token=$secureToken&x-oss-process=$process"`都没有效果.

请问能添加一下这个功能吗? 谢谢 [文档地址](https://help.aliyun.com/zh/oss/user-guide/img-implementation-modes/?spm=a2c4g.11186623.0.0.638a327aQAVlBf)

**Comment by huhx** [comment]
已经在6.4.0提供支持：

```dart
final String url = await Client().getSignedUrl(
  "test.jpg",
  params: {"x-oss-process": "image/resize,w_10/quality,q_90"},
);
```

**Comment by JianJia2018** [comment]
感谢, 已使用, 没问题.
