### ISSUE TITLE
判断文件是否存在接口

### ISSUE THREAD

**Issue by zKidor** [huhx/flutter_oss_aliyun#49]
看了一下插件接口，没有找到判断oss文件是否存在的功能，在oss文档里面是有的，接口是doesObjectExist，
https://help.aliyun.com/zh/oss/developer-reference/determine-whether-an-object-exists-7?spm=a2c4g.11186623.0.0.5daa37b3Iczlhl
有计划添加吗？

**Comment by huhx** [comment]
version: 6.4.1提供支持

```dart
final bool isExisted = await Client().doesObjectExist(
    "aaa.jpg",
);
```

**Comment by zKidor** [comment]
判断文件存在功能正常，感谢支持
