### ISSUE TITLE
报错Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by xaiocaiji7653** [huhx/flutter_oss_aliyun#52]
为啥所有的这行代码 await Client().putObject(  都报错Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'
flutter版本3.18.0
dart版本3.3.0
求大佬解答

**Comment by huhx** [comment]
有可以复现的小 demo 吗

**Comment by xaiocaiji7653** [comment]
> 有可以复现的小 demo 吗
直接用pub仓库给的example都会报错
// ignore: depend_on_referenced_packages
import 'package:flutter/foundation.dart';
// ignore: depend_on_referenced_packages
import 'package:flutter/material.dart';
import 'package:flutter_appointment_photography/net/http_constant.dart';
import 'package:flutter_oss_aliyun/flutter_oss_aliyun.dart';

// void main() {
//   runApp(
//     const MaterialApp(
//       debugShowCheckedModeBanner: false,
//       home: HomeScreen(),
//     ),
//   );
// }

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  void initState() {
    super.initState();
    Client.init(
      stsUrl: HttpConstant.stsUrl,
      ossEndpoint: "oss-cn-chengdu.aliyuncs.com",
      bucketName: "ap-photo-server",
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Flutter aliyun oss example"),
      ),
      body: Container(
        alignment: Alignment.center,
        child: Column(
          children: [
            TextButton(
              onPressed: () async {
                final bytes = Uint8List.fromList("Hello World".codeUnits);
                await Client().putObject(
                  bytes,
                  "filename.txt",
                  option: PutRequestOption(
                    onSendProgress: (count, total) {
                      if (kDebugMode) {
                        print("send: count = $count, and total = $total");
                      }
                    },
                    onReceiveProgress: (count, total) {
                      if (kDebugMode) {
                        print("receive: count = $count, and total = $total");
                      }
                    },
                    override: false,
                    aclModel: AclMode.private,
                    storageType: StorageType.standard,
                    callback: const Callback(
                      callbackUrl: "callbackUrl",
                      callbackBody:
                          "{\"mimeType\":\${mimeType}, \"filepath\":\${object},\"size\":\${size},\"bucket\":\${bucket},\"phone\":\${x:phone}}",
                      callbackVar: {"x:phone": "android"},
                      calbackBodyType: CalbackBodyType.json,
                    ),
                  ),
                );
              },
              child: const Text("Upload object"),
            ),
            TextButton(
              onPressed: () async {
                await Client().getObject(
                  "filename.txt",
                  onReceiveProgress: (count, total) {
                    debugPrint("received = $count, total = $total");
                  },
                );
              },
              child: const Text("Get object"),
            ),
            TextButton(
              onPressed: () async {
                await Client().downloadObject(
                  "filename.txt",
                  "./example/savePath.txt",
                  onReceiveProgress: (count, total) {
                    debugPrint("received = $count, total = $total");
                  },
                );
              },
              child: const Text("Download object"),
            ),
            TextButton(
              onPressed: () async {
                await Client().deleteObject("filename.txt");
              },
              child: const Text("Delete object"),
            ),
            TextButton(
              onPressed: () async {
                await Client().putObjects(
                  [
                    AssetEntity(
                      filename: "filename1.txt",
                      bytes: "files1".codeUnits,
                      option: PutRequestOption(
                        onSendProgress: (count, total) {
                          if (kDebugMode) {
                            print("send: count = $count, and total = $total");
                          }
                        },
                        onReceiveProgress: (count, total) {
                          if (kDebugMode) {
                            print(
                                "receive: count = $count, and total = $total");
                          }
                        },
                        override: true,
                        aclModel: AclMode.inherited,
                      ),
                    ),
                    AssetEntity(
                        filename: "filename2.txt", bytes: "files2".codeUnits),
                  ],
                );
              },
              child: const Text("Batch upload object"),
            ),
            TextButton(
              onPressed: () async {
                await Client()
                    .deleteObjects(["filename1.txt", "filename2.txt"]);
              },
              child: const Text("Batch delete object"),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by xaiocaiji7653** [comment]
> 有可以复现的小 demo 吗

![image](https://github.com/huhx/flutter_oss_aliyun/assets/94792991/517feba7-dcbc-41a6-91e5-80b3d7f8069c)

**Comment by huhx** [comment]
<img width="1202" alt="image" src="https://github.com/huhx/flutter_oss_aliyun/assets/15972372/10ae07d3-bb71-4e7b-9ffc-107b3beba58f">

```dart

 test("test the put test in Client", () async {
    final String string = "Hello World";

    final Response<dynamic> resp = await Client().putObject(
      Uint8List.fromList(utf8.encode(string)),
      "test-test.txt",
      option: PutRequestOption(
        onSendProgress: (count, total) {
          print("send: count = $count, and total = $total");
        },
        onReceiveProgress: (count, total) {
          print("receive: count = $count, and total = $total");
        },
        override: true,
        aclModel: AclMode.publicRead,
        storageType: StorageType.ia,
        callback: Callback(
          callbackUrl: callbackUrl,
          callbackBody:
              "{\"mimeType\":\${mimeType}, \"filepath\":\${object},\"size\":\${size},\"bucket\":\${bucket},\"phone\":\${x:phone}}",
          callbackVar: {"x:phone": "android"},
          calbackBodyType: CalbackBodyType.json,
        ),
      ),
    );
```

**Comment by xaiocaiji7653** [comment]
还是不行，但是我改了client.dart文件里面的代码成功了，但是访问oss报错403
![client](https://github.com/huhx/flutter_oss_aliyun/assets/94792991/81405996-4dbb-44dc-92c7-c6839defbce3)
![image](https://github.com/huhx/flutter_oss_aliyun/assets/94792991/d92c5c98-0740-4015-9fc4-abc0fe6f6a48)

**Comment by huhx** [comment]
如果是提供了 stsUrl，那么需要返回的json结构如下 

```json
{
  "AccessKeyId": "AccessKeyId",
  "AccessKeySecret": "AccessKeySecret",
  "SecurityToken": "SecurityToken",
  "Expiration": "2022-03-22T11:33:06Z"
}
```
这是我后端返回的例子：
<img width="298" alt="image" src="https://github.com/huhx/flutter_oss_aliyun/assets/15972372/e8b7d208-005c-41dc-b012-16cccf2c85e2">

**Comment by xaiocaiji7653** [comment]
> 如果是提供了 stsUrl，那么需要返回的json结构如下
> 
> ```json
> {
>   "AccessKeyId": "AccessKeyId",
>   "AccessKeySecret": "AccessKeySecret",
>   "SecurityToken": "SecurityToken",
>   "Expiration": "2022-03-22T11:33:06Z"
> }
> ```
> 
> 这是我后端返回的例子： <img alt="image" width="298" src="https://private-user-images.githubusercontent.com/15972372/310373712-e8b7d208-005c-41dc-b012-16cccf2c85e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDM3MjAsIm5iZiI6MTcwOTcwMzQyMCwicGF0aCI6Ii8xNTk3MjM3Mi8zMTAzNzM3MTItZThiN2QyMDgtMDA1Yy00MWRjLWIwMTItMTZjY2NmMmM4NWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1MzcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZWRmY2RlMjM4MTczMDAyODdiNzU0YzI3ZTBlZTY0NWE3MjJkZmQ0MDIyNTRiYjBjMDhhOGJjZTc4MGVkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KP1Ew5pPjCT8FHps8ruhM4CeM-1Ajr1K3LrvMup3CM4">

这是我的，顺序不一样有影响吗？
![Uploading image.png…]()

**Comment by xaiocaiji7653** [comment]
> 如果是提供了 stsUrl，那么需要返回的json结构如下
> 
> ```json
> {
>   "AccessKeyId": "AccessKeyId",
>   "AccessKeySecret": "AccessKeySecret",
>   "SecurityToken": "SecurityToken",
>   "Expiration": "2022-03-22T11:33:06Z"
> }
> ```
> 
> 这是我后端返回的例子： <img alt="image" width="298" src="https://private-user-images.githubusercontent.com/15972372/310373712-e8b7d208-005c-41dc-b012-16cccf2c85e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDM5NzUsIm5iZiI6MTcwOTcwMzY3NSwicGF0aCI6Ii8xNTk3MjM3Mi8zMTAzNzM3MTItZThiN2QyMDgtMDA1Yy00MWRjLWIwMTItMTZjY2NmMmM4NWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1NDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZmYzODNhMjVhODZlZTcxNmFmZGRhNDc5ZDRkZjlkMmFhMTYxMDI3NThmZWI1N2YyNDRlZWRkOTVmOWQ1YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UsBdj0Jr67UEtRn9DWljjjnRivti8sj5Foas1TEXGpA">

这是我的，顺序不一样有影响吗？
![image](https://github.com/huhx/flutter_oss_aliyun/assets/94792991/1774ad02-e3b9-4619-a1e1-5292b8248371)

**Comment by huhx** [comment]
结构是没问题，你是说文件上传成功了(可以在 aliyun 网页上面检查)，但是访问文件报403?

**Comment by xaiocaiji7653** [comment]
文件没上传成功，只是从后端成功获取了sts凭证，但是用sts凭证上传文件的时候报403了，我怀疑是阿里云角色权限问题，但是重新创建了还是403

**Comment by xaiocaiji7653** [comment]
> 结构是没问题，你是说文件上传成功了(可以在 aliyun 网页上面检查)，但是访问文件报403?

文件没上传成功，只是从后端成功获取了sts凭证，但是用sts凭证上传文件的时候报403了，我怀疑是阿里云角色权限问题，但是重新创建了还是403

**Comment by xaiocaiji7653** [comment]
成功了，就是我权限没设置好，感谢大佬
