### ISSUE TITLE
flutter web在上传视频文件时，页面会冻结无法操作

### ISSUE THREAD

**Issue by con-9** [huhx/flutter_oss_aliyun#58]
使用本插件上传视频文件到阿里云时，能正常获得上传期间的回调，但是在完全上传成功前，页面是不可操作的状态，有什么好的方法解决。

**Comment by huhx** [comment]
有两个方向

- 一个是使用Isolate，参考https://docs.flutter.dev/perf/isolates

- 另一个是workmanager，参考: https://pub.dev/packages/workmanager

**Comment by con-9** [comment]
> 有两个方向
> 
> * 一个是使用Isolate，参考https://docs.flutter.dev/perf/isolates
> * 另一个是workmanager，参考: https://pub.dev/packages/workmanager

这两个在web端好像都不支持

**Comment by con-9** [comment]
选择用js来实现传输就不会有冻结情况了
