### ISSUE TITLE
secureToken,客户端可以自己生成吗？

### ISSUE THREAD

**Issue by Nuyoahhjh** [huhx/flutter_oss_aliyun#61]

**Comment by huhx** [comment]
可以，参考：https://github.com/huhx/flutter_oss_aliyun?tab=readme-ov-file#2-%E8%87%AA%E5%AE%9A%E4%B9%89authgetter%E5%BE%97%E5%88%B0auth

**Comment by Nuyoahhjh** [comment]
![image](https://github.com/user-attachments/assets/d7a62534-3b84-4fef-83d7-46d7cc975ab4)

上传文件提示403，可是我用同样的信息拿去ossBrowser测试是ok的 @huhx

**Comment by Nuyoahhjh** [comment]
通了

**Comment by Nuyoahhjh** [comment]
可以指定文件夹上传吗
