### ISSUE TITLE
Sys Url 从哪里拿到？阿里云文档中没有指出

### ISSUE THREAD

**Issue by Arbureva** [huhx/flutter_oss_aliyun#64]
能否给个地址，我搜了半天都没有搜到从哪里拿到的stsUrl，还以为是ARN

**Comment by markofrain** [comment]
stsUrl就是你后台自己写的一个获取秘钥和token的服务端地址。这个服务端地址的方法里面是需要你根据ARN信息调用阿里云的sts包得到的临时秘钥和token。
https://help.aliyun.com/zh/oss/developer-reference/use-temporary-access-credentials-provided-by-sts-to-access-oss?scm=20140722.S_help%40%40%E6%96%87%E6%A1%A3%40%40100624.S_BB1%40bl%2BBB2%40bl%2BRQW%40ag0%2Bhot%2Bos0.ID_100624-RL_sts-LOC_doc%7EUND%7Eab-OR_ser-V_4-P0_0&spm=a2c4g.11186623.0.i59

https://api.aliyun.com/api/Sts/2015-04-01/AssumeRole?spm=a2c4g.11186623.0.0.21394676krZb6E&RegionId=

**Comment by Arbureva** [comment]
好的明白
