### ISSUE TITLE
Can you provide the url of local signature access file

### ISSUE THREAD

**Issue by panhuiAipami** [huhx/flutter_oss_aliyun#9]
You can see that your getObject is asynchronous. Can you provide a temporary access address for local signatures? That is, you can directly view the file link in the browser

thank you！

**Comment by huhx** [comment]
final Response<dynamic> resp = await Client().getObject( "filename1.txt");
final url = resp.requestOptions.path;

You can get the url from the response

**Comment by panhuiAipami** [comment]
Since the resource is private, sts signature is required to obtain temporary access credentials, which cannot be accessed directly through this link

**Comment by huhx** [comment]
> Since the resource is private, sts signature is required to obtain temporary access credentials, which cannot be accessed directly through this link

Hi, I find a useful link. Maybe it will help to implement what you want. It will take times to do it since I am a little busy due to my job. 

May I ask you that you use this package in web?

link: https://help.aliyun.com/document_detail/31952.html

**Comment by panhuiAipami** [comment]
Alioss provides SDKs generated from temporary access addresses of sts on multiple platforms, but there is no flutter. Can we write a dart version with reference to the code of other platforms

**Comment by huhx** [comment]
> Alioss provides SDKs generated from temporary access addresses of sts on multiple platforms, but there is no flutter. Can we write a dart version with reference to the code of other platforms

Yes, it is possible. But need time to achieve this goal. And also I will appreciate the upcoming PR from anyone.

**Comment by panhuiAipami** [comment]
> > Alioss provides SDKs generated from temporary access addresses of sts on multiple platforms, but there is no flutter. Can we write a dart version with reference to the code of other platforms
> 
> Yes, it is possible. But need time to achieve this goal. And also I will appreciate the upcoming PR from anyone.

OK, your plug-in is very good. I'm using it in the Flutter project. I've encountered this problem so far. Thank you!

**Comment by huhx** [comment]
> > > Alioss provides SDKs generated from temporary access addresses of sts on multiple platforms, but there is no flutter. Can we write a dart version with reference to the code of other platforms
> > 
> > 
> > Yes, it is possible. But need time to achieve this goal. And also I will appreciate the upcoming PR from anyone.
> 
> OK, your plug-in is very good. I'm using it in the Flutter project. I've encountered this problem so far. Thank you!

Thank you. I am doing this feature in my spare time. Once i finished it, I will let you know.

**Comment by huhx** [comment]
add the feature of getting singed url in version: ^3.1.0

**Comment by panhuiAipami** [comment]
> add the feature of getting singed url in version: ^3.1.0

nice !  thanks
